<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreOrderRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'quantity' => 'required|int|min:1',
            'remarks' => 'required',
            'payment_method' => 'required'
        ];
    }

    public function messages(): array
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'quantity.required' => 'Quantity is required',
            'remarks.required' => 'Remarks is required for user experience',
            'payment_method.required' => 'Choose Payment Method'
        ];
    }
}
